version: '3.3'
services:
  reader:
    image: virtualwolf/pi-sensor-reader:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ./config.json:/opt/service/config.json
      - ./queue:/opt/service/queue
